# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"save_16bit": "README.ipynb",
         "distort_coords": "README.ipynb",
         "undistort_array": "README.ipynb",
         "get_essential": "README.ipynb",
         "get_fundamental": "README.ipynb",
         "fusi_rigid_rect": "README.ipynb",
         "fusi_cam_rect": "README.ipynb",
         "rect_homography": "README.ipynb",
         "rect_array": "README.ipynb",
         "boug_rigid_rect": "README.ipynb",
         "boug_cam_rect": "README.ipynb"}

modules = ["None.py",
           "image_rect.py"]

doc_url = "https://justinblaber.github.io/image_rect/"

git_url = "https://github.com/justinblaber/image_rect/tree/master/"

def custom_doc_links(name): return None
